### ISSUE TITLE
Ejercicio Herencia Libro

### ISSUE THREAD

**Issue by ivanjimenez** [avellanedaDaw1/ProgramacionDAW#14]
Se quiere informatizar una biblioteca. Crea las clases Publicacion,Libroy Revista. Las clases deben estar implementadas con la jerarquía correcta. Las características comunes de las revistas y de los libros son el código ISBN, el título, y el año de publicación. Los libros tienen además un atributo prestado.

Cuando se crean los libros, no están prestados. Las revistas tienen un número.La clase Libro debe implementar la interfaz Prestable que tiene los métodos presta, devuelve y estaPrestado.
```bash
Publicación<------<<es un>>---Libro------> implementa <<interfaz>> Prestable
       ^                                                 
       |    <<es un>>                                                
       |
  Revista                  
```

**Comment by javierbarbe** [comment]
//CLASE PADRE
public abstract class Biblioteca {

	protected int ISBN, anio;
	protected String titulo;

}
//CLASES HIJAS 
//REVISTA 
public class Revista extends Biblioteca{

		private int numero;

		public int getNumero() {
			return numero;
		}

		public void setNumero(int numero) {
			this.numero = numero;
		}
}
//LIBRO
public class Libro extends Biblioteca implements Prestable {
	private boolean prestado=false; 
	public void presta() {
		prestado=true;
	}
	public void devuelve() {
		prestado=false;
	}

	public boolean estaPrestado() {
		return prestado;
	}
	
}

//INTERFAZ
public interface Prestable {
	public void presta();
	public void devuelve();
	public boolean estaPrestado();
}

**Comment by ivanjimenez** [comment]
La clase Biblioteca sería Publicacion. Está correcto el ejercicio pero realiza algunos métodos toString para poder imprimir mensajes y una clase Test para probar y así verificas su funcionamiento.
