### ISSUE TITLE
8C no hay video

### ISSUE THREAD

**Issue by javierbarbe** [avellanedaDaw1/ProgramacionDAW#16]
bBuenas ivan
El apartado 8C que indica que sigamos las instrucciones de un video para realizar los ejercicios siguientes no contiene tal video.
Por si lo puedes pasar el enlace o una breve explicacion
Un saludo 
y feliz cuarentena

**Comment by ivanjimenez** [comment]
Hola, Javier:
Pues ahí estamos aguantando todos esta situación. Espero que tengáis espacio para poder pasearos un poco. Ahora mismo subo un recurso equivalente a ese video, el enlace está roto. Gracias
